name: ecoguardian
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  carousel_slider: any

  # Firebase dependencies
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  firebase_database: ^11.0.3
  cloud_firestore: ^5.1.0
  firebase_storage: ^12.1.1

  # Other dependencies
  google_maps_flutter: ^2.2.2
  image_picker: ^0.8.5+3

  location: ^4.4.0
  http: ^0.13.3
  url_launcher: ^6.0.20
  flutter_staggered_animations: ^1.0.0
  animated_text_kit: ^4.2.1
  youtube_player_iframe: ^2.3.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/image1.jpg
    - assets/image2.jpg
    - assets/image3.jpg
    - assets/image4.jpg
    - assets/image5.jpg
    - assets/image6.jpg
    - assets/image7.jpg
    - assets/image8.jpg
    - assets/image9.jpg
    - assets/image10.jpg
    - assets/image11.jpg
    - assets/image12.jpg
    - assets/image13.jpg

