name: ecoguardian
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  carousel_slider: any

  # Firebase dependencies
  firebase_core: ^3.2.0  # Ensure this version or higher
  firebase_auth: ^5.1.2  # Ensure this version or higher
  firebase_database: ^11.0.3  # Example version; adjust as needed
  # Add other Firebase plugins as needed, e.g., firebase_storage, firebase_messaging

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/image1.jpg
    - assets/image2.jpg
    - assets/image3.jpg
    - assets/image4.jpg
    - assets/image5.jpg
    - assets/image6.jpg
    - assets/image7.jpg
